### ISSUE TITLE
how to wiki  support task list

### ISSUE THREAD

**Issue by cenggel** [gitbucket/gitbucket#1022]
I am work with gitbucket 3.9 how to insert task list in wiki? I'm write task list like flow style but not work.

```
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```

**Comment by takezoe** [comment]
Currently, GitBucket supports task list in issue, pull request and their comment. Not supported in wiki. However we add task list support in wiki to our to-do list.

**Comment by eprozium** [comment]
plug-in functionality?
