### ISSUE TITLE
Deprecate the plugin registry

### ISSUE THREAD

**Issue by takezoe** [gitbucket/gitbucket#2321]
Currently, we host official plugins at the plugin registry. It automates plugin build and provides network installation of hosted plugins. However we don't have much time to well maintain it.

Originally, we launched the plugin registry to reduce the cost for building plugins per GitBucket release because if GitBucket API is changed, recompile is necessary in plugins. However, GitBucket API is more stable than before, so we don't benefit from the plugin registry these days.

Also, we had wanted to expand the plugin registry covering to third-party plugins. However there are many problem to solve before that like security issue, server resources and of course, human resource to maintainis is one of them. 

For these reasons, I would like to shutdown the plugin registory as the release of GitBucket 4.32.0.

## Tasks

- [x] Update [sbt-gitbucket-plugin](https://github.com/gitbucket/sbt-gitbucket-plugin) to remove GitBucket version from the assembly jar name
- [x] Update plugin management system
  - [x] Drop network plugin installation functionallity (#2322)
  - [x] Bundle default plugins again
- [x] Prepare GitBucket 4.32.0 release
  - [x] Set entry size in creating an archive file (#2324)
- [x] Update official plugins to use GitBucket 4.32.0 and sbt-gitbucket-plugin 1.5.0
  - [x] gitbucket-notification-plugin (https://github.com/gitbucket/gitbucket-notifications-plugin/pull/14)
  - [x] gitbucket-gist-plugin (https://github.com/gitbucket/gitbucket-gist-plugin/pull/57)
  - [x] gitbucket-emoji-plugin (https://github.com/gitbucket/gitbucket-emoji-plugin/pull/8)
  - [x] gitbucket-pages-plugin (https://github.com/gitbucket/gitbucket-pages-plugin/pull/25)
- [x] Update [gitbucket-plugin-template](https://github.com/gitbucket/gitbucket-plugin-template) to use GitBucket 4.32.0 and sbt-gitbucket-plugin 1.5.0

**Comment by aadrian** [comment]
@takezoe what about the new https://github.com/features/package-registry functionality ? Would that solve the problem?

**Comment by takezoe** [comment]
@aadrian Thanks for your comment. I think the release page on GitHub is good enough for providing plugin jar files as we had used it before starting the plugin registry.
