### ISSUE TITLE
Pages for each milestones

### ISSUE THREAD

**Issue by onukura** [gitbucket/gitbucket#2579]
### Before submitting an issue to GitBucket I have first:

- [x] read the [contribution guidelines](https://github.com/gitbucket/gitbucket/blob/master/.github/CONTRIBUTING.md)
- [x] searched for similar already existing issue
- [x] read the documentation and [wiki](https://github.com/gitbucket/gitbucket/wiki)

*(if you have performed all the above, remove the paragraph and continue describing the issue with template below)*

## Issue
**Impacted version**: 4.34

Currently GitBucket does not have page for each milestones. 
We just can access each milestone by url `/owner/:repository/issues?milestone={name}&state=open`.

It would be nice if there is page for each milestone at url `/:owner/:repository/milestone/:id` like GitHub.
